def_widget_opts! {
    TkButtonOpt: (
        // standard
        TkActiveBackground,
        TkActiveForeground,
        TkAnchor,
        TkBackground,
        TkBg,
        TkBitmap,
        TkBorderWidth,
        TkBd,
        TkCompound,
        TkCursor,
        TkDisabledForeground,
        TkFont,
        TkForeground,
        TkHighlightBackground,
        TkHighlightColor,
        TkHighlightThickness,
        TkImage,
        TkJustify,
        TkPadX,
        TkPadY,
        TkRelief,
        TkRepeatDelay,
        TkRepeatInterval,
        TkTakeFocus,
        TkText,
        TkTextVariable,
        TkUnderline,
        TkWrapLength,

        // widget-specific
        TkCommand,
        TkDefault,
        TkHeight,
        TkOverRelief,
        TkState,
        TkWidth,
    ),
}
