def_widget_opts! {
    TkEntryOpt: (
        // standard
        TkBackground,
        TkBg,
        TkCursor,
        TkExportSelection,
        TkFont,
        TkForeground,
        TkHighlightBackground,
        TkHighlightColor,
        TkHighlightThickness,
        TkInsertBackground,
        TkInsertBorderWidth,
        TkInsertOffTime,
        TkInsertOnTime,
        TkInsertWidth,
        TkJustify,
        TkRelief,
        TkSelectBackground,
        TkSelectBorderWidth,
        TkSelectForeground,
        TkTakeFocus,
        TkTextVariable,
        TkXScrollCommand,
        TkUnderline,
        TkWrapLength,

        // widget-specific
        TkDisabledBackground,
        TkDisabledForeground,
        TkInvalidCommand,
        TkReadOnlyBackground,
        TkShow,
        TkState,
        TkValidate,
        TkValidateCommand,
        TkWidth,
    ),
}
