def_widget_opts! {
    TkMenuOpt: (
        // standard
        TkActiveBackground,
        TkActiveBorderWidth,
        TkActiveForeground,
        TkBackground,
        TkBg,
        TkBorderWidth,
        TkBd,
        TkCursor,
        TkDisabledForeground,
        TkFont,
        TkForeground,
        TkRelief,
        TkTakeFocus,

        // widget-specific
        TkPostCommand,
        TkSelectColor,
        TkTearOff,
        TkTearOffCommand,
        TkTitle,
        TkType,
    ),
    TkMenuEntryOpt: (
        TkActiveBackground,
        TkActiveForeground,
        TkAccelerator,
        TkBackground,
        TkBitmap,
        TkColumnBreak,
        TkCommand,
        TkCompound,
        TkFont,
        TkForeground,
        TkHideMargin,
        TkImage,
        TkIndicatorOn,
        TkLabel,
        TkMenu,
        TkOffValue,
        TkOnValue,
        TkSelectColor,
        TkSelectImage,
        TkState,
        TkUnderline,
        TkValue,
        TkVariable,
    ),
}
