def_widget_opts! {
    TkScaleOpt: (
        // standard
        TkActiveBackground,
        TkBackground,
        TkBg,
        TkBorderWidth,
        TkBd,
        TkCursor,
        TkFont,
        TkForeground,
        TkHighlightBackground,
        TkHighlightColor,
        TkHighlightThickness,
        TkOrient,
        TkRelief,
        TkRepeatDelay,
        TkRepeatInterval,
        TkTakeFocus,
        TkTroughColor,

        // widget-specific
        TkBigIncrement,
        TkCommand,
        TkDigits,
        TkFrom,
        TkLabel,
        TkLength,
        TkResolution,
        TkShowValue,
        TkSliderLength,
        TkSlideRelief,
        TkState,
        TkTickInterval,
        TkTo,
        TkVariable,
        TkWidth,
    ),
}
