def_widget_opts! {
    TkSpinboxOpt: (
        // standard
        TkActiveBackground,
        TkBackground,
        TkBg,
        TkBorderWidth,
        TkBd,
        TkCursor,
        TkExportSelection,
        TkFont,
        TkForeground,
        TkHighlightBackground,
        TkHighlightColor,
        TkHighlightThickness,
        TkInsertBackground,
        TkInsertBorderWidth,
        TkInsertOffTime,
        TkInsertOnTime,
        TkInsertWidth,
        TkJustify,
        TkRelief,
        TkRepeatDelay,
        TkRepeatInterval,
        TkSelectBackground,
        TkSelectBorderWidth,
        TkSelectForeground,
        TkTakeFocus,
        TkTextVariable,
        TkXScrollCommand,

        // widget-specific
        TkButtonBackground,
        TkButtonCursor,
        TkButtonDownRelief,
        TkButtonUpRelief,
        TkCommand,
        TkDisabledBackground,
        TkDisabledForeground,
        TkFormat,
        TkFrom,
        TkInvalidCommand,
        TkInvCmd,
        TkIncrement,
        TkReadOnlyBackground,
        TkState,
        TkTo,
        TkValidate,
        TkValidateCommand,
        TkValues,
        TkWidth,
        TkWrap,
    ),
}
